--[[
    TODO:
    Implement Roact UI Creation
    Implement Listeners that replace the old roblox ones due to how we override the entire chat system
    Client-To-Server System that lets the server do much more
    Filter (Roblox did this so its not hard to implement)
    Between Script Communication
    Toggle Button for uis (currently planning on using TopBarPlus to simulate the look of roblox)
    Easier way to add Tags, TextColor, Fonts, UIScaling, Positioning
    ReImplement the lost systems due to the chat not utilizing ANY roblox chat service items
    Support for Nicknames, DisplayNames. Aswell as the option to see the username if you hover over the name
    Custom Non Roact UI Support
    Custom Chat Command Support
    Custom Colour name support

    Later releases -
    TeamChat
    /t support
]]